version: '3'

services:
  nginx:
    image: nginx:1.15.7-alpine
    container_name: nimakoo_nginx
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs/:/var/log/nginx/
    ports:
      - ${APP_PORT:-0}:80
    working_dir: /app
    restart: always
    depends_on:
      - php

  php:
    build: ./docker/php/fpm
    image: nimakoo_php
    container_name: nimakoo_php
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
